---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
  shellcheck:
    enabled: true
    checks:
      SC2034:
        enabled: false
ratings:
  paths:
  - "**.rb"
  - "**.sh"
exclude_paths: []
